### ISSUE TITLE
Circular Buffer

### ISSUE THREAD

**Issue by roberttidey** [roberttidey/userland#1]
Would be good to have Circular buffer built in to raspimjpeg. So continuously recording to buffer when motion detection active. Start trigger records to file. Stop trigger prepends the buffer and closes file.

Some useful code is modified raspivid at 

https://github.com/ethanol100/userland/commit/63dbcb4b016b0d697e391990985cd7c7a20ea4df

**Comment by silvanmelchior** [comment]
I have some freetime this weekend, so I'm going to give it a try, this is also the top item on my wishlist, it would be very useful and a lot of people already asked for it
