### ISSUE TITLE
Nested media_path directory

### ISSUE THREAD

**Issue by josh18** [roberttidey/userland#11]
There seems to be an issue when setting `media_path` to be a sibling directory of `image_path`. For example:

This works
```
image_path /home/pi/camera/images/%D-%M-%Y-%h-%m-%s.jpg
media_path /home/pi/camera
```

This doesn't
```
image_path /home/pi/camera/images/%D-%M-%Y-%h-%m-%s.jpg
media_path /home/pi/camera/thumbnails
```

Thumbnails aren't generated but there doesn't seem to be any errors in the log file (full size image saves fine). Is it expected to be able to work with a structure like this? Same permissions for both so I don't think it is something like that.

**Comment by roberttidey** [comment]
Currently the paths (image, video, lapse) are expected to share the same root as the media_path. This allows finding the media files directly from the thumbnail image names even if the paths themselves have subfolders (e.g. /home/pi/camera/images/%D-%M-%Y/%h-%m-%s.jpg )

To avoid confusion It would have been better to define these paths as relative to the root media_path (e.g. 
`image_path /images/%D-%M-%Y-%h-%m-%s.jpg`
but that wasn't the way the software grew and I am reluctant to change it to avoid breaking existing set ups.

Note that you can effectively achieve your set up by using link commands to specify where the files actually go even though they are still defined as hierarchical.

**Comment by josh18** [comment]
Ah I see, I thought it might be something like that. I should be able to work around it without too much trouble. Thanks for your help!
