### ISSUE TITLE
Pipe command "im" captures multiple images

### ISSUE THREAD

**Issue by ristaloff** [roberttidey/userland#3]
I have raspimjpeg v.5.1.3 running, and its continuously updating this image /dev/shm/cam.jpeg. While this is running I send a command to the command-pipe like this `echo "im" > /var/www/FIFO`
This causes new images to appear in /var/www/media/. It continues to capture images to this folder until I send this command: `echo "" > /var/www/FIFO`

How can I send a command to the pipe so it only captures a single image?
I've also tried to send "im 1" and "im 0" with the same result.

**Comment by roberttidey** [comment]
cam.jpg should be updating all the time; that feeds the live preview.

The im processing sounds weird. I just tried this and just get one image. I do use the following command 
echo -n 'im' >/var/www/FIFO
The -n switch means don't put a LF on the end and that may be making the difference. The Pipe input processor doesn't need that. Having said that I tried without the -n and still got a single image.

Also you can look at the schedulerLog as it gets logging reports from raspimjpeg as it processes each pipe command.

Can you also say where your echo is coming from.? Is it just from a command line or within some other process?

**Comment by ristaloff** [comment]
I tried with the command you used. It still captures a lot of images.
schedulerLog looks like this:
....
{2015/04/23 13:30:17} Capturing image
{2015/04/23 13:30:17} Capturing image
{2015/04/23 13:30:17} Capturing image
{2015/04/23 13:30:18} Capturing image
{2015/04/23 13:30:18} Capturing image
{2015/04/23 13:30:18} Capturing image
{2015/04/23 13:30:19} Capturing image
{2015/04/23 13:30:19} Capturing image
{2015/04/23 13:30:19} Capturing image
{2015/04/23 13:30:19} Capturing image
{2015/04/23 13:30:19} Capturing image
{2015/04/23 13:30:20} Capturing image
{2015/04/23 13:30:20} Capturing image
{2015/04/23 13:30:20} Capturing image
{2015/04/23 13:30:20} Capturing image
{2015/04/23 13:30:20} Capturing image
{2015/04/23 13:30:20} Capturing image
{2015/04/23 13:30:20} Capturing image
....

I'm running the echo command manually from the command-line.

I've started raspimjpeg with no parameters. Just relaying on the /etc/raspimjpeg config file. 
`sudo raspimjpeg`

**Comment by ristaloff** [comment]
I solved it!
Hehe really stupid of me, but the /var/www/FIFO file was a regular file. And not a pipe.
Weird that most commands actually worked anyway.

Thanks for your fast reply and helping me out!

**Comment by roberttidey** [comment]
OK. That makes sense. Raspimjpeg reading from a pipe empties it whereas from a file it just sees the same stuff over again.
