### ISSUE TITLE
Fix README_RaspiMJPEG.md

### ISSUE THREAD

**Issue by ristaloff** [roberttidey/userland#4]
The README_RaspiMJPEG.md file needs better formatting and some of the possible pipe commands need better desciption. Like the Flip command. What does the range [0:3] translate to in terms of HFlip and VFLip?
And are alle the parameters to the pipe commands in decimal or are some in hex?

**Comment by silvanmelchior** [comment]
The idea is to move all documentation to the wiki and remove this file. So
if you want to improve the documentation and contribute to the wiki, it
would be very appreciated ;)

**Comment by roberttidey** [comment]
Yes. There already is a pipe command table in the wiki http://elinux.org/RPi-Cam-Web-Interface#Pipe

It does not spell out flip out any more, but that is the right place to add extra info. All values are decimal

**Comment by ristaloff** [comment]
Ok. I just feel it's more natural to have to raspimjpeg specific documentation in the Readme_raspimjpeg.md file. Then the documentation is also under source control and follows the raspimjpeg version. A link to this documentation can be provided in the the wiki. 
I think it should be easy to install and start using raspimjpeg without needing to know anything about the RPI_Web_interface.

**Comment by ristaloff** [comment]
I just updated the description of the flip command in the wiki now.

**Comment by roberttidey** [comment]
Thanks for the  doc update.

Maintaining the info here would make more sense if raspimjpeg was primarily used as a standalone user installed application, but it isn't. This repository is publishing and maintaining a core component. You are obviously free to use it as a component in other apps, but there is no installer here for it outside of the RPI_Web material. So you would need ti install it yourself, set up a PIPE interface for commands etc.

Most people will be starting from the pre-built version under RPi Cam and they will want the reference material for things like the pipe commands which they can directly use.

**Comment by ristaloff** [comment]
Yes, I kind-of understand that. It was a bit hard to set up as a standalone application, because I had to go through the "RPi_Cam_Web_Interface_Installer.sh" to find out how to set up the PIPE, folders, permissions etc. I think of the RPI_Web as just a showcase for what you can do with raspimjpeg. And when it's time to use raspimjpeg in your own project then you'll only want to download and install raspimjpeg without the RPI_Web. In my case I did not want to download the and run the RPI_web installer script beacuse I already had nginx installed and I wanted to use that instead of apache.
